apiVersion: v1
kind: Service
metadata:
  name: sonicmoving-platform-service-frontend
  labels:
    name: sonicmoving-platform-service-frontend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: sonicmoving-platform-service-frontend
  type: ClusterIP
